### ISSUE TITLE
how to download img?

### ISSUE THREAD

**Issue by moshuying** [guitaoliu/MSI-GS63VR-Hackintosh#1]
i cant use your efi (macOS Big Sur 11.0.1 20B50 Installer for CLOVER 5126 and OpenCore 0.6.3 and PE 32G.dmg),I want your mac dmg download url,can you help me?

**Comment by guitaoliu** [comment]
Sorry, I can't help you with that. But I forgot to mention in the README that I have deleted the entire SMBIOS ( (`MacBookPro14,3` works for me)) section in [config.plist](https://github.com/guitaoliu/MSI-GS63VR-Hackintosh/blob/master/EFI/OC/config.plist), which may prevent you from booting. Also, you need to follow the [OpenCore manual](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#intel-bios-settings) to carefully modify your BIOS settings.
