### ISSUE TITLE
大佬好，HDMI无法连接。Cannot connect HDMI

### ISSUE THREAD

**Issue by Yehuw** [guitaoliu/MSI-GS63VR-Hackintosh#2]

**Comment by guitaoliu** [comment]
这款机器（MSI GS63VR）的 HDMI 接口是接在独立显卡上的，独立显卡没办法驱动，因而 HDMI 无法使用，可以考虑修改 USE MAPPING 开启 type-c 接口并使用转接头使用，另外，c 口在 hackintosh 下使用需要先插上设备再启动系统。

**Comment by BoronFan** [comment]
请问USE MAPPING具体需要修改哪个文件呢？刚需Type-C外接显示器，求指教

> 这款机器（MSI GS63VR）的 HDMI 接口是接在独立显卡上的，独立显卡没办法驱动，因而 HDMI 无法使用，可以考虑修改 USE MAPPING 开启 type-c 接口并使用转接头使用，另外，c 口在 hackintosh 下使用需要先插上设备再启动系统。

**Comment by guitaoliu** [comment]
你可以直接使用 [USBInjectAll.kext](https://github.com/Sniki/OS-X-USB-Inject-All/releases) 替换 USBPorts.kext 并设置 Kernel–Quirks-XhciPortLimit 为 true 即可暂时解决，关于 usb mapping 可以参考 https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html

**Comment by BoronFan** [comment]
懂了，感谢！

> 你可以直接使用 [USBInjectAll.kext](https://github.com/Sniki/OS-X-USB-Inject-All/releases) 替换 USBPorts.kext 并设置 Kernel–Quirks-XhciPortLimit 为 true 即可暂时解决，关于 usb mapping 可以参考 https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html

**Comment by guitaoliu** [comment]
如果没有进一步的问题我就关掉这个issue了
