### ISSUE TITLE
headphone output

### ISSUE THREAD

**Issue by yinruonan** [guitaoliu/MSI-GS63VR-Hackintosh#3]
hello, can i adjust the volume of the headphone output?

**Comment by guitaoliu** [comment]
The volume of wired headphones cannot be adjusted. [SoundSource](https://rogueamoeba.com/soundsource/) could be a solution to that. And the speakers and wireless headphones are working fine.

**Comment by yinruonan** [comment]
> The volume of wired headphones cannot be adjusted. [SoundSource](https://rogueamoeba.com/soundsource/) could be a solution to that. And the speakers and wireless headphones are working fine.

好嘞，蓝牙的可以。这工具可以控制spdif音量嘛？
