### ISSUE TITLE
Is MSI GS63VR 6rf compatible? 

### ISSUE THREAD

**Issue by ericshen90** [guitaoliu/MSI-GS63VR-Hackintosh#4]
CPU: 6th gen i7-6700HQ

**Comment by guitaoliu** [comment]
This repo is only compatible with MSI GS63VR 7rf. You can follow the [OpenCore Installation Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html) to modify the config.plist and other files.

**Comment by ericshen90** [comment]
> This repo is only compatible with MSI GS63VR 7rf. You can follow the [OpenCore Installation Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html) to modify the config.plist and other files.

TKS
