### ISSUE TITLE
Wifi还需要再去配置itlwm吗

### ISSUE THREAD

**Issue by Xingzhe-Tung** [guitaoliu/MSI-GS63VR-Hackintosh#5]
如题，请问大佬，我把这里的EFI引导替换了黑果小兵的镜像成功安装了mac os，但是发现wlan和airdrop都没办法用，需要再去配置itlwm吗

**Comment by guitaoliu** [comment]
即使是使用itlwm也是[无法驱动AirDrop](https://openintelwireless.github.io/itlwm/FAQ.html#does-it-support-apple-s-continuity-framework-airdrop-handoff)的，最好的办法是更换Broadcom的网卡

**Comment by Xingzhe-Tung** [comment]
好的，看到项目里的截图错以为能驱动了，感谢大佬回复

**Comment by guitaoliu** [comment]
我应该是忘了注明更换过网卡了，后续可以添加下说明

**Comment by guitaoliu** [comment]
没有什么问题我就关闭这个issue了
