### ISSUE TITLE
显示器亮度 按键位置似乎不正确

### ISSUE THREAD

**Issue by Pl6ME** [guitaoliu/MSI-GS63VR-Hackintosh#6]
就是这款笔记本  
DW1560装上了  win 10 下wifi信号显示很差是通病？

**Comment by guitaoliu** [comment]
WiFi这个应该没有好的解决办法了，要么舍弃部分功能使用 [itlwm](https://github.com/OpenIntelWireless/itlwm) 驱动其他的无线网卡。按键应该可以自己做映射的。
