### ISSUE TITLE
显示色深问题

### ISSUE THREAD

**Issue by JeskaiJet** [guitaoliu/MSI-GS63VR-Hackintosh#7]
感谢配置，成功启动了macOS，并且大部分功能正常运作。
但是貌似集成显卡的驱动不太正常，显示透明过渡的颜色很不自然，如图：
<img width="461" alt="image" src="https://user-images.githubusercontent.com/10975080/137592538-2d682231-e25f-402b-bba6-70f43fc5acff.png">
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/10975080/137592665-5b0fda03-319b-4e3e-87c6-b359b7239532.png">
并且系统报告中色彩深度只有24位（应该是30位）
<img width="336" alt="image" src="https://user-images.githubusercontent.com/10975080/137592694-7accc567-a737-4c71-9572-707f128b5e3b.png">
请问是否有解决方法？

**Comment by guitaoliu** [comment]
这个我不是很清楚欸，显卡这里我是直接用的 [Hackintool](https://github.com/headkaze/Hackintool)

**Comment by JeskaiJet** [comment]
我才发现原来即使截图了在其他设备上看也是正常的...
不过我已经找到了解决办法了
<img width="641" alt="image" src="https://user-images.githubusercontent.com/10975080/137613863-22cc558f-4836-41f4-af4b-b490e40e4c02.png">
把原先的显卡配置改成这样就好了
PS:顺便还要在boot-args内添加`lilucpu=8`
