### ISSUE TITLE
请问在Monterey系统下是否可以正常唤醒？

### ISSUE THREAD

**Issue by liamgf** [guitaoliu/MSI-GS63VR-Hackintosh#9]
我这边升级Monterey之后，睡眠后唤醒是黑屏，按键盘也没有任何反应

**Comment by guitaoliu** [comment]
睡眠是个比较复杂的问题，可以参照[这里](https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html)逐一排查

**Comment by liamgf** [comment]
请问您这边升级Monterey之后睡眠是否正常呢？我自己配的OC在Big Sur睡眠正常，升级Monterey之后睡眠唤醒是黑屏，然后我试了一下您的OC也是一样的问题，不知道是哪里的问题，所以想确认一下您这边Monterey睡眠唤醒是否正常？

**Comment by guitaoliu** [comment]
我这边的情况好像是直接进入不了睡眠
